### ISSUE TITLE
Link for dowload on windows does not work

### ISSUE THREAD

**Issue by arhoy** [thedevsaddam/docgen-bin#2]
The following link give me 404
https://github.com/thedevsaddam/docgen-bin/blob/master/v2.4/windows_amd64.zip

**Comment by dipanshuchaubey** [comment]
Here is the file https://github.com/thedevsaddam/docgen-bin/tree/master/v2

**Comment by thedevsaddam** [comment]
@arhoy use [this link](https://github.com/thedevsaddam/docgen-bin/blob/master/v2.4/windows_amd64.exe.zip)

> Need to fix the link

**Comment by Anondo** [comment]
> @arhoy use [this link](https://github.com/thedevsaddam/docgen-bin/blob/master/v2.4/windows_amd64.exe.zip)
> 
> > Need to fix the link

No need for this link. The links provided in the doc should work fine now.
